[package]
name = "tomoru_test_task"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"]}

# Serde / json
serde = { version = "1", features = ["derive"] }

# Web
axum = { version = "0.8", features = ["macros"]}
axum-client-ip = "0.7.0"



